version: 1.2
tools:
   - subclass: cwl
     primaryDescriptorPath: /tools/Dockstore.cwl
     publish: false
workflows:
   - subclass: cwl
     primaryDescriptorPath: /workflows/HelloWorld.cwl
     publish: false
